apiVersion: netbird.io/v1alpha1
kind: Group
metadata:
  name: kubernetes-services
  namespace: netbird
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  name: kubernetes-services

---

apiVersion: netbird.io/v1alpha1
kind: Group
metadata:
  name: kubernetes-clients
  namespace: netbird
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  name: kubernetes-clients

---

apiVersion: netbird.io/v1
kind: NBPolicy
metadata:
  name: kubernetes-access
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  name: kubernetes-access
  description: Peers in kubernetes-clients may reach the exposed Kubernetes services
  sourceGroups:
    - kubernetes-clients
  destinationGroups:
    - kubernetes-services
  protocols:
    - tcp
  ports:
    - 80
    - 4005
    - 7007
    - 8080
    - 8200
  bidirectional: false
