apiVersion: netbird.io/v1alpha1
kind: NetworkRouter
metadata:
  name: proxy
  namespace: netbird
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  dnsZoneRef:
    name: proxy.rjst.de
