apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: vault
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  networkRouterRef:
    name: proxy
    namespace: netbird
  serviceRef:
    name: vault
  groups:
    - name: kubernetes-services
