apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: vault
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  networkRouterRef:
    name: proxy
    namespace: netbird
  serviceRef:
    name: vault
  groups:
    - name: All

---

apiVersion: v1
kind: Secret
metadata:
  namespace: vault
  name: vault-unsealer-config
  labels:
    vault-unsealer.bakito.net/stateful-set: vault
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    avp.kubernetes.io/path: "argocd/data/vault"
type: Opaque
stringData:
  unsealKey1: <unsealKey1>
  unsealKey2: <unsealKey2>
  unsealKey3: <unsealKey3>
  unsealKey4: <unsealKey4>
  unsealKey5: <unsealKey5>
