apiVersion: netbird.io/v1alpha1
kind: Group
metadata:
  name: kubernetes-services
  namespace: netbird
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  name: kubernetes-services

---

apiVersion: netbird.io/v1alpha1
kind: Group
metadata:
  name: kubernetes-clients
  namespace: netbird
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  name: kubernetes-clients
