---
docker_hosts:
   - docker01
   - ansible01

mariadb_hosts:
   - ansible01

postgresql_hosts:
   - ansible01
   - docker01

mongodb_hosts:
   - ansible01

node_exporter_hosts:
   - ansible01

# Add hostnames here once netbird_setup_key is provided (ansible-vault or --extra-vars)
netbird_hosts:
   - k8sdev01
