title: Overview
language: de
bookmarksStyle: icons
background:
  brightness: 50
  opacity: 20
headerStyle: clean
statusStyle: dot

layout:
  Infrastruktur:
    style: row
    columns: 4
  Künstliche Intelligenz:
    style: row
    columns: 3
  Streaming & Medien:
    style: row
    columns: 3
  Finanzen:
    style: row
    columns: 4
  Hosting & Server:
    style: row
    columns: 4
  Hardware & Shopping:
    style: row
    columns: 3
  Entwicklung:
    style: row
    columns: 2
  Gaming:
    style: row
    columns: 2
