apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/ToXiCCuss/gitops.git
    targetRevision: master
    path: kubernetes/cicd/helm
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-kubectl
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/ToXiCCuss/gitops.git
    targetRevision: master
    path: kubernetes/cicd/kubectl
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
