services:
  wings:
    container_name: pelican_wings
    image: ghcr.io/pelican/wings:v1.0.0-beta29@sha256:39837cfc49b0513313e57dc4b977a769cb784cf81af3f25a5ea46d869b4b0846
    restart: always
    networks:
      - wings0
    ports:
      - "8080:8080"
      - "2022:2022"
    environment:
      TZ: "Europe/Berlin"
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pelican
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
      - "/etc/pelican/:/etc/pelican/"
      - "/var/lib/pelican/:/var/lib/pelican/"
      - "/var/log/pelican/:/var/log/pelican/"
      - "/tmp/pelican/:/tmp/pelican/"
networks:
  wings0:
    name: wings0
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: wings0
