apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db
  namespace: keycloak
  annotations:
    avp.kubernetes.io/path: "argocd/data/keycloak"
type: Opaque
stringData:
  username: <postgresql.username>
  password: <postgresql.password>
