apiVersion: v1
kind: Secret
metadata:
  name: microcks-mongodb-connection
  namespace: microcks
  annotations:
    avp.kubernetes.io/path: "argocd/data/microcks"
type: Opaque
stringData:
  username: <username>
  password: <password>
