apiVersion: v1
kind: Secret
metadata:
  name: netbird-mgmt-api-key
  namespace: netbird
  annotations:
    avp.kubernetes.io/path: "argocd/data/netbird"
type: Opaque
stringData:
  NB_API_KEY: <api_key>
