apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: example-apicurioregistry-mem
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  configuration:
    persistence: "mem"


---

apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: apicurio-registry
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  networkRouterRef:
    name: proxy
    namespace: netbird
  serviceRef:
    name: example-apicurioregistry-mem-service
