services:
  seaweedfs:
    env_file:
      - ".env"
    image: chrislusf/seaweedfs@sha256:08d516132314207d10c8e37cbffc1f32b147d870169688734cc61c6231625b62
    container_name: seaweedfs
    ports:
      - "8333:8333"
      - "23646:23646"
      - "8888:8888"
    restart: unless-stopped
    volumes:
      - "/root/docker/seaweedfs:/data"

