services:
  databasus:
    container_name: databasus
    image: databasus/databasus:v3.56.0@sha256:e2ae939db08c0cf48c2ff1d6d32b05805c3983d6a350be756e9cd741dd96d6c4
    ports:
      - "4005:4005"
    volumes:
      - /root/docker/databasus:/databasus-data
    restart: unless-stopped
