services:
  databasus:
    container_name: databasus
    image: databasus/databasus:v3.54.0@sha256:4b312c2ed58243086449114294443ae6219f1cc8afb583d850971d3c71af27a7
    ports:
      - "4005:4005"
    volumes:
      - /root/docker/databasus:/databasus-data
    restart: unless-stopped
    networks:
      - internal_net

networks:
  internal_net:
    name: internal_net
    internal: true
