services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v2.1.2@sha256:da9dca9ec258c628146bed1445da0853f2b88f0b10bafd97c091de807c363d60
    container_name: homepage
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    environment:
      HOMEPAGE_ALLOWED_HOSTS: overview.proxy.rjst.de
      PUID: 1000
      PGID: 1000
    networks:
      - external_net

networks:
  external_net:
    name: external_net
    external: true
