apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: management
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/ToXiCCuss/gitops.git
    targetRevision: master
    path: kubernetes/management
    directory:
      recurse: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
