services:
  netbird-client:
    container_name: netbird-client
    hostname: <HOSTNAME>
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    networks:
      - internal_net
      - external_net
    environment:
      - NB_SETUP_KEY=<SETUP KEY>
    volumes:
      - netbird-client:/var/lib/netbird
    image: netbirdio/netbird:latest
volumes:
  netbird-client:
    name: netbird-client

networks:
  internal_net:
    name: internal_net
    internal: true
  external_net:
    name: external_net
    external: true
