apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: backstage
  namespace: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  networkRouterRef:
    name: proxy
    namespace: netbird
  serviceRef:
    name: backstage
  groups:
    - name: kubernetes-services
