services:
  duplicati:
    image: duplicati/duplicati:2.4.0.0-stable@sha256:eb0c1298a1974048332745b393897ae3cc1c20258e4fc26a796f2b5d75eb6218
    container_name: duplicati
    volumes:
      - /root/docker/duplicati:/data
      - /:/source
    ports:
      - "8200:8200"
    env_file:
      - "default.env"
      - ".env"
    restart: unless-stopped
