services:
  arcane:
    image: ghcr.io/getarcaneapp/manager:v2.13.0@sha256:6220640fe97c0d2b96ba0502ec60d057c501e78bcab2bd88f4338a251dc1f75e
    container_name: arcane
    ports:
      - '3552:3552'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/docker/arcane/data:/app/data
      - /root/docker/arcane/backups:/backups
    env_file:
      - "default.env"
      - "override.env"
    restart: unless-stopped
