services:
  arcane:
    image: ghcr.io/getarcaneapp/manager:v2.12.0@sha256:7304d54948626355e11a855dbcde49f58468c71e4cbf43b5315d3a2f5fd01a58
    container_name: arcane
    ports:
      - '3552:3552'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/docker/arcane/data:/app/data
      - /root/docker/arcane/backups:/backups
    env_file:
      - "default.env"
      - "override.env"
    restart: unless-stopped
